// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: finish_send_job.proto

package finish_send_job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinishSendJobMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time                  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	RequestHeaderLocation *string                `protobuf:"bytes,2,opt,name=request_header_location,json=requestHeaderLocation" json:"request_header_location,omitempty"`
	LogTime               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=log_time,json=logTime" json:"log_time,omitempty"`
	Uuid                  *string                `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
}

func (x *FinishSendJobMsg) Reset() {
	*x = FinishSendJobMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finish_send_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishSendJobMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSendJobMsg) ProtoMessage() {}

func (x *FinishSendJobMsg) ProtoReflect() protoreflect.Message {
	mi := &file_finish_send_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSendJobMsg.ProtoReflect.Descriptor instead.
func (*FinishSendJobMsg) Descriptor() ([]byte, []int) {
	return file_finish_send_job_proto_rawDescGZIP(), []int{0}
}

func (x *FinishSendJobMsg) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *FinishSendJobMsg) GetRequestHeaderLocation() string {
	if x != nil && x.RequestHeaderLocation != nil {
		return *x.RequestHeaderLocation
	}
	return ""
}

func (x *FinishSendJobMsg) GetLogTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LogTime
	}
	return nil
}

func (x *FinishSendJobMsg) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

var File_finish_send_job_proto protoreflect.FileDescriptor

var file_finish_send_job_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6a, 0x6f,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6a, 0x6f, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x10, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x53, 0x65, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x4d, 0x73, 0x67, 0x12, 0x2e,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x36,
	0x0a, 0x17, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x15, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6a, 0x6f, 0x62,
}

var (
	file_finish_send_job_proto_rawDescOnce sync.Once
	file_finish_send_job_proto_rawDescData = file_finish_send_job_proto_rawDesc
)

func file_finish_send_job_proto_rawDescGZIP() []byte {
	file_finish_send_job_proto_rawDescOnce.Do(func() {
		file_finish_send_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_finish_send_job_proto_rawDescData)
	})
	return file_finish_send_job_proto_rawDescData
}

var file_finish_send_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_finish_send_job_proto_goTypes = []interface{}{
	(*FinishSendJobMsg)(nil),      // 0: finish_send_job.FinishSendJobMsg
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_finish_send_job_proto_depIdxs = []int32{
	1, // 0: finish_send_job.FinishSendJobMsg.time:type_name -> google.protobuf.Timestamp
	1, // 1: finish_send_job.FinishSendJobMsg.log_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finish_send_job_proto_init() }
func file_finish_send_job_proto_init() {
	if File_finish_send_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finish_send_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishSendJobMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finish_send_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_finish_send_job_proto_goTypes,
		DependencyIndexes: file_finish_send_job_proto_depIdxs,
		MessageInfos:      file_finish_send_job_proto_msgTypes,
	}.Build()
	File_finish_send_job_proto = out.File
	file_finish_send_job_proto_rawDesc = nil
	file_finish_send_job_proto_goTypes = nil
	file_finish_send_job_proto_depIdxs = nil
}
